image: maven:latest

variables:
  CODECLIMATE_VERSION: latest

test_our_code:
  stage: test
  script:
    - mvn test
    
codequality:
    before_script: []
    stage: test
    image: docker:stable
    variables:
        DOCKER_DRIVER: overlay2
    allow_failure: true
    services:
        - docker:stable-dind
    script:
        - export cc_opts="--env CODECLIMATE_DEBUG=1 --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc"
        - docker run ${cc_opts} "codeclimate/codeclimate:${CODECLIMATE_VERSION}" analyze -f html > codeclimate.html
        - docker run ${cc_opts} "codeclimate/codeclimate:${CODECLIMATE_VERSION}" analyze -f json > codeclimate.json
    artifacts:
        paths: [codeclimate.html, codeclimate.json]
